### ISSUE TITLE
Can't drag-and-drop principal color chip

### ISSUE THREAD

**Issue by mikegoodstadt** [stephan-mclean/project-color#29]
Hi Stephan - nice tool!
I am not sure if it is meant to function as I expect but the principal color chip cannot be dragged to the Palette/Pairs area.
On the Variant page, all the others smaller chip below (lighter, darker, saturated) **can** be dragged and dropped into the Palette/Pairs area.
All the best with your projects :)
Mike

**Comment by stephan-mclean** [comment]
Hi Mike, 

Thank you very much! 

This app is still very much a work in progress. There are a bunch of items I still have left to do. 

The functionality you're describing is one of those things I need to do. It should be available in the coming days as I add the code :) 

Thanks again! 

Stephen

**Comment by mikegoodstadt** [comment]
I admire you getting to this level - always a challenge too get the point you feel comfortable publishing - this app feels well more the WIP!

**Comment by stephan-mclean** [comment]
Thank you! It's true, but it also means I can get some good feedback by putting it out there 😊 

Thanks for taking the time to look at my app and create an issue. I just merged a PR which solves the dragging problem. Hopefully, you find the app useful!
